### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by MaxPleaner** [abhshkdz/HackFlowy#27] opened 2016-02-01 23:04 UTC
I tried running this with a static http server (`python -m SimpleHTTPServer 3000`) and was able to see the index file, however it was in 'offline' mode and was failing to connect the Tasks API on port 3000.

I tried running with `node server.js` but that's where I get the error in this issue's header. 

I got the same error on heroku. Have been trying to fix, but unsuccessful. 

I also tried making an express ` get '/'` route which rendered part of the index page. None of the app assets (including scripts and styles) were loaded though. 

```sh
$ node --version
v0.10.37
$ npm --version
n3.5.3
$ more /etc/*-release | grep DISTRIB_DESCRIPTION
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
$ uname -r
3.19.0-49-generic
```

**Comment by wassname** [comment] 2016-02-02 01:00
For the static server, that's expected behaviour. Offline mode means you haven't got a server running.

For running the server can you post error output?

**Comment by wassname** [comment] 2016-02-02 01:16
Oh it looks like this might be because I merge gh-pages into master by accident. Should be fixed soon. In the meantime if you grab wassname/HackFlowy/master it should work when running `node server.js`?

**Comment by wassname** [comment] 2016-02-02 06:24
Should be fixed in the main repo now, feel free to reopen this with more info otherwise.

**Comment by MaxPleaner** [comment] 2016-02-02 08:19
@wassname theres some crazy stuff going on when node server.js is run locally and it's not working. The server seems to be making some repetetive query. Do you mind me asking if you tried cloning the repo, running `sudo npm install` and `bower install`, then `node server.js`?

Here'es the query which is run repeatedly upon opening `localhost:3000`;

```txt
Executing (default): SELECT `id`, `content`, `parentId`, `isCompleted`, `priority`, `isFolded`, `createdAt`, `updatedAt` FROM `Tasks` AS `Tasks` WHERE `Tasks`.`id` = '981b915d-16c4-4d72-9987-722db2b9dcd7';
Executing (default): UPDATE `Tasks` SET `priority`=787,`updatedAt`='2016-02-02 08:17:21.000 +00:00' WHERE `id` = '95cafe50-993a-41c2-8395-f36b866d8bb1'
{ view: 'put(\'/tasks/:id)',
  id: '8ab6bb2a-d64e-43af-881d-5f9c28bb9fa1',
  body: 
   { id: '8ab6bb2a-d64e-43af-881d-5f9c28bb9fa1',
     content: '',
     parentId: '00000000-0000-0000-0000-000000000000',
     isCompleted: false,
     priority: 790,
     isFolded: false,
     createdAt: '2016-02-02T08:17:01.000Z',
     updatedAt: '2016-02-02T08:17:01.000Z' } }

txt

**Comment by MaxPleaner** [comment] 2016-02-02 08:23
@wassname if you want to see a 1-click Heroku deploy I just launched, view https://maxp-hackflowy1.herokuapp.com/

you will see that it freezes.

**Comment by wassname** [comment] 2016-02-02 08:25
Hi yeah I have tried it worked for me. I get the same output, it's just some `console.log(x,y)` from server.js. Feel free to make it better and make PR.

**Comment by wassname** [comment] 2016-02-02 08:28
Nice, that herokuapp show whats going on. If you go to https://maxp-hackflowy1.herokuapp.com/tasks it gives an empty json array, so there is nothing in the server DB. In that case we might want to look at the deploy logs to see if there where errors in DB population.

Also on the frontend it can't find a few dependencies. Did `bower install` work I wonder.

This is what it should look like: http://abhshkdz.github.io/HackFlowy

**Comment by wassname** [comment] 2016-02-02 08:33
I'll try deploying from scratch again and get back to you.  it might not be until tomorrow though as it's getting late in Australasia.

 thanks for testing it by the way, I appreciate it and it will iron out any problems. I do want to get deploy working smoothly so dev's can easily jump in and contribute.

**Comment by wassname** [comment] 2016-02-02 11:25
Solved, I had a look at the build log on heroku and the problems showed up. It was:
 - bower not being called during heroku deploy, fixed by adding it to package.json postinstall hook
- in the production env postgres didn't like the id's of the demo data, this was shown in the build log, fixed this too

I also removed the that verbose output, so it doesn't look crazy on startup

**Closed by wassname** 2016-02-02 11:25 UTC
Labels: question
